version: '3.7'

services:
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
      image: cordy09/infra_api:v1
      restart: always
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
      depends_on:
        - db
      env_file:
        - ./.env
  nginx:
      image: nginx:1.21.3-alpine
      ports:
        - "81:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

        - static_value:/var/html/static/

        - media_value:/var/html/media/
      depends_on:
        - web

volumes:
  static_value:
  media_value:
